# Generated by Django 4.2.21 on 2025-10-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_googlebotvisit_verified_google_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('path_accessed', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
